# Generated by Django 5.2.14 on 2026-05-11 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игрока'), ('active', 'В процессе'), ('finished', 'Завершена')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world_width', models.IntegerField(default=16)),
                ('world_height', models.IntegerField(default=12)),
                ('player1_side', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия')], max_length=10)),
                ('player2_side', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия')], max_length=10)),
                ('player1_mr', models.IntegerField(default=100)),
                ('player2_mr', models.IntegerField(default=100)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('is_player1_first', models.BooleanField(default=True)),
                ('move_number', models.IntegerField(default=1)),
                ('winner', models.CharField(blank=True, choices=[('french', 'Франция'), ('russian', 'Россия')], max_length=10, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('infantry', 'Линейная пехота'), ('grenadier', 'Гренадёры'), ('huntsman', 'Егеря'), ('guardsman', 'Гвардейская пехота'), ('dragoon', 'Драгуны'), ('hussar', 'Гусары'), ('ulan', 'Уланы'), ('horse_huntsman', 'Конные егеря'), ('cuirassier', 'Кирасиры'), ('artillery', 'Артиллерия'), ('horse_artillery', 'Конная артиллерия')], max_length=20)),
                ('army', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия')], max_length=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('last_used_turn', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='game.game')),
            ],
        ),
    ]
