# Generated by Django 5.2.13 on 2026-04-14 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn_number', models.IntegerField(default=1)),
                ('first_side', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия'), ('austrian', 'Австрия')], default='russian', max_length=10)),
                ('second_side', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия'), ('austrian', 'Австрия')], default='french', max_length=10)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('infantry', 'Пехота'), ('hussar', 'Гусары'), ('cuirassier', 'Кирасиры'), ('artillery', 'Артиллерия')], max_length=20)),
                ('army', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия'), ('austrian', 'Австрия')], max_length=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='game.game')),
            ],
        ),
    ]
