# Generated by Django 5.2.13 on 2026-05-04 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игрока'), ('active', 'В процессе'), ('finished', 'Завершена')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn_number', models.IntegerField(default=1)),
                ('first_side', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия'), ('austrian', 'Австрия')], default='russian', max_length=10)),
                ('second_side', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия'), ('austrian', 'Австрия')], default='french', max_length=10)),
                ('winner', models.CharField(blank=True, choices=[('french', 'Франция'), ('russian', 'Россия'), ('austrian', 'Австрия')], max_length=10, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('infantry', 'Линейная пехота'), ('hussar', 'Гусары'), ('dragoon', 'Драгуны'), ('cuirassier', 'Кирасиры'), ('artillery', 'Артиллерия'), ('horse_artillery', 'Конная артиллерия')], max_length=20)),
                ('army', models.CharField(choices=[('french', 'Франция'), ('russian', 'Россия'), ('austrian', 'Австрия')], max_length=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('last_used_turn', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='game.game')),
            ],
        ),
    ]
