# Generated by Django 5.2.13 on 2026-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('french', 'Франция'), ('russian', 'Россия'), ('austrian', 'Австрия')], max_length=10, null=True),
        ),
    ]
