# Generated by Django 5.2.13 on 2026-04-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='last_used_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('infantry', 'Линейная пехота'), ('hussar', 'Гусары'), ('dragoon', 'Драгуны'), ('cuirassier', 'Кирасиры'), ('artillery', 'Артиллерия'), ('horse_artillery', 'Конная артиллерия')], max_length=20),
        ),
    ]
